project_root: ~/projects
rview:
  - command: basename {REPO}
    label: Repo
  - command: git -C {REPO} -c color.ui=always rev-parse --abbrev-ref HEAD
    label: Active Branch
  - command: git -C {REPO} -c color.ui=always status
    label: Status
  - command: cat {REPO}/README.md
    label: README 