project_root: %USERPROFILE%\projects
rview:
  - command: powershell -Command "Split-Path -Leaf {REPO}"
    label: Repo
  - command: git -C {REPO} -c color.ui=always rev-parse --abbrev-ref HEAD
    label: Active Branch
  - command: git -C {REPO} -c color.ui=always status
    label: Status
  - command: type {REPO}\README.md
    label: README 